
version: '3.4'


services:
  zookeeper1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      #- 2181:2181
      - 2182:2181
    environment:
        ZOO_MY_ID: 1
#        ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
#
#  zookeeper2:
#    image: zookeeper
#    restart: always
#    hostname: zoo2
#    ports:
#      #- 2181:2181
#      - 2182:2181
#    environment:
#        ZOO_MY_ID: 1
#        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
#
#  zookeeper3:
#    image: zookeeper
#    restart: always
#    hostname: zoo3
#    ports:
#      #- 2181:2181
#      - 2182:2181
#    environment:
#        ZOO_MY_ID: 1
#        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
